{
    "openapi": "3.0.1",
    "info": {
        "title": "个人项目",
        "description": "",
        "version": "1.0.0"
    },
    "tags": [
        {
            "name": "示例项目"
        },
        {
            "name": "宠物"
        }
    ],
    "paths": {
        "/pet/{petId}": {
            "get": {
                "summary": "查询宠物详情",
                "deprecated": false,
                "description": "",
                "tags": [
                    "示例项目",
                    "宠物"
                ],
                "parameters": [
                    {
                        "name": "petId",
                        "in": "path",
                        "description": "宠物 ID",
                        "required": true,
                        "example": "1",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 0,
                                            "description": "状态码"
                                        },
                                        "data": {
                                            "$ref": "#/components/schemas/Pet",
                                            "description": "宠物信息"
                                        }
                                    },
                                    "required": [
                                        "code",
                                        "data"
                                    ]
                                },
                                "examples": {
                                    "1": {
                                        "summary": "成功示例",
                                        "value": {
                                            "code": 0,
                                            "data": {
                                                "name": "Hello Kity",
                                                "photoUrls": [
                                                    "http://dummyimage.com/400x400"
                                                ],
                                                "id": 3,
                                                "category": {
                                                    "id": 71,
                                                    "name": "Cat"
                                                },
                                                "tags": [
                                                    {
                                                        "id": 22,
                                                        "name": "Cat"
                                                    }
                                                ],
                                                "status": "sold"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "headers": {}
                    },
                    "400": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "code",
                                        "message"
                                    ]
                                }
                            }
                        },
                        "headers": {}
                    },
                    "404": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "message": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "code",
                                        "message"
                                    ]
                                }
                            }
                        },
                        "headers": {}
                    }
                },
                "security": []
            },
            "delete": {
                "summary": "删除宠物信息",
                "deprecated": false,
                "description": "",
                "tags": [
                    "示例项目",
                    "宠物"
                ],
                "parameters": [
                    {
                        "name": "petId",
                        "in": "path",
                        "description": "Pet id to delete",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "api_key",
                        "in": "header",
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 0
                                        }
                                    },
                                    "required": [
                                        "code"
                                    ]
                                },
                                "examples": {
                                    "1": {
                                        "summary": "成功示例",
                                        "value": {
                                            "code": 0
                                        }
                                    }
                                }
                            }
                        },
                        "headers": {}
                    }
                },
                "security": []
            }
        },
        "/pet": {
            "post": {
                "summary": "新建宠物信息",
                "deprecated": false,
                "description": "",
                "tags": [
                    "示例项目",
                    "宠物"
                ],
                "parameters": [],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {}
                            },
                            "example": {
                                "id": "1"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 0
                                        },
                                        "data": {
                                            "$ref": "#/components/schemas/Pet",
                                            "description": "宠物信息"
                                        }
                                    },
                                    "required": [
                                        "code",
                                        "data"
                                    ]
                                },
                                "examples": {
                                    "1": {
                                        "summary": "成功示例",
                                        "value": {
                                            "code": 0,
                                            "data": {
                                                "name": "Hello Kity",
                                                "photoUrls": [
                                                    "http://dummyimage.com/400x400"
                                                ],
                                                "id": 3,
                                                "category": {
                                                    "id": 71,
                                                    "name": "Cat"
                                                },
                                                "tags": [
                                                    {
                                                        "id": 22,
                                                        "name": "Cat"
                                                    }
                                                ],
                                                "status": "sold"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "headers": {}
                    }
                },
                "security": []
            },
            "put": {
                "summary": "修改宠物信息",
                "deprecated": false,
                "description": "",
                "tags": [
                    "示例项目",
                    "宠物"
                ],
                "parameters": [],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {}
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "data": {
                                            "$ref": "#/components/schemas/Pet",
                                            "description": "宠物信息"
                                        }
                                    },
                                    "required": [
                                        "code",
                                        "data"
                                    ]
                                },
                                "examples": {
                                    "1": {
                                        "summary": "成功示例",
                                        "value": {
                                            "code": 0,
                                            "data": {
                                                "name": "Hello Kity",
                                                "photoUrls": [
                                                    "http://dummyimage.com/400x400"
                                                ],
                                                "id": 3,
                                                "category": {
                                                    "id": 71,
                                                    "name": "Cat"
                                                },
                                                "tags": [
                                                    {
                                                        "id": 22,
                                                        "name": "Cat"
                                                    }
                                                ],
                                                "status": "sold"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "headers": {}
                    },
                    "404": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {}
                                }
                            }
                        },
                        "headers": {}
                    },
                    "405": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {}
                                }
                            }
                        },
                        "headers": {}
                    }
                },
                "security": []
            }
        },
        "/pet/findByStatus": {
            "get": {
                "summary": "根据状态查找宠物列表",
                "deprecated": false,
                "description": "",
                "tags": [
                    "示例项目",
                    "宠物"
                ],
                "parameters": [
                    {
                        "name": "status",
                        "in": "query",
                        "description": "Status values that need to be considered for filter",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Pet",
                                        "description": "宠物信息"
                                    }
                                },
                                "examples": {
                                    "1": {
                                        "summary": "成功示例",
                                        "value": {
                                            "code": 0,
                                            "data": [
                                                {
                                                    "name": "Hello Kity",
                                                    "photoUrls": [
                                                        "http://dummyimage.com/400x400"
                                                    ],
                                                    "id": 3,
                                                    "category": {
                                                        "id": 71,
                                                        "name": "Cat"
                                                    },
                                                    "tags": [
                                                        {
                                                            "id": 22,
                                                            "name": "Cat"
                                                        }
                                                    ],
                                                    "status": "sold"
                                                },
                                                {
                                                    "name": "White Dog",
                                                    "photoUrls": [
                                                        "http://dummyimage.com/400x400"
                                                    ],
                                                    "id": 3,
                                                    "category": {
                                                        "id": 71,
                                                        "name": "Dog"
                                                    },
                                                    "tags": [
                                                        {
                                                            "id": 22,
                                                            "name": "Dog"
                                                        }
                                                    ],
                                                    "status": "sold"
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        },
                        "headers": {}
                    },
                    "400": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    },
                                    "required": [
                                        "code"
                                    ]
                                }
                            }
                        },
                        "headers": {}
                    }
                },
                "security": []
            }
        },
        "/test": {
            "post": {
                "summary": "测试接口",
                "deprecated": false,
                "description": "",
                "tags": [
                    "示例项目",
                    "宠物"
                ],
                "parameters": [
                    {
                        "name": "formId",
                        "in": "query",
                        "description": "表单id",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "bookId",
                        "in": "query",
                        "description": "书籍ID",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "name": "tags",
                        "in": "query",
                        "description": "标签",
                        "required": false,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer",
                                        "description": "ID 编号"
                                    },
                                    "status": {
                                        "type": "integer",
                                        "description": "状态"
                                    },
                                    "keyword": {
                                        "type": "string"
                                    },
                                    "tags": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "name": {
                                                    "type": "string"
                                                },
                                                "id": {
                                                    "type": "integer"
                                                }
                                            },
                                            "required": [
                                                "id"
                                            ]
                                        }
                                    },
                                    "obj": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "age": {
                                                "type": "integer"
                                            }
                                        },
                                        "required": [
                                            "name"
                                        ]
                                    }
                                },
                                "required": [
                                    "id",
                                    "status",
                                    "tags",
                                    "obj"
                                ]
                            },
                            "example": {
                                "null": null,
                                "id": 1,
                                "status": 10,
                                "keyword": "测试",
                                "tags": [
                                    {
                                        "name": "标签一",
                                        "id": 1
                                    },
                                    {
                                        "name": "标签一",
                                        "id": 1
                                    }
                                ],
                                "obj": {
                                    "name": "小明",
                                    "age": 18
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 0
                                        },
                                        "data": {
                                            "$ref": "#/components/schemas/Pet",
                                            "description": "宠物信息"
                                        }
                                    },
                                    "required": [
                                        "code",
                                        "data"
                                    ]
                                },
                                "examples": {
                                    "1": {
                                        "summary": "成功示例",
                                        "value": {
                                            "code": 0,
                                            "data": {
                                                "name": "Hello Kity",
                                                "photoUrls": [
                                                    "http://dummyimage.com/400x400"
                                                ],
                                                "id": 3,
                                                "category": {
                                                    "id": 71,
                                                    "name": "Cat"
                                                },
                                                "tags": [
                                                    {
                                                        "id": 22,
                                                        "name": "Cat"
                                                    }
                                                ],
                                                "status": "sold"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "headers": {}
                    }
                },
                "security": []
            }
        }
    },
    "components": {
        "schemas": {
            "Tag": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "minimum": 1,
                        "description": "标签ID编号"
                    },
                    "name": {
                        "type": "string",
                        "description": "标签名称"
                    }
                },
                "xml": {
                    "name": "Tag"
                }
            },
            "Category": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "minimum": 1,
                        "description": "分组ID编号"
                    },
                    "name": {
                        "type": "string",
                        "description": "分组名称"
                    }
                },
                "xml": {
                    "name": "Category"
                }
            },
            "Pet": {
                "required": [
                    "name",
                    "photoUrls",
                    "id",
                    "category",
                    "tags",
                    "status"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "minimum": 1,
                        "description": "宠物ID编号"
                    },
                    "category": {
                        "$ref": "#/components/schemas/Category",
                        "description": "分组"
                    },
                    "name": {
                        "type": "string",
                        "description": "名称",
                        "examples": [
                            "doggie"
                        ]
                    },
                    "photoUrls": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "照片URL"
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Tag"
                        },
                        "description": "标签"
                    },
                    "status": {
                        "type": "string",
                        "description": "宠物销售状态",
                        "enum": [
                            "available",
                            "pending",
                            "sold"
                        ]
                    }
                }
            }
        },
        "securitySchemes": {}
    },
    "servers": []
}